image:
  name: "tgcslearningtech/grade-nodejs"
  entrypoint: [""]

stages:
  - test

MochaTests:
  stage: test
  script:
    - /usr/local/bin/start-mongo.sh
    - npm install
    - npm run test-own
  timeout: "600"

sonarqube-check:
  image:
    name: "tgcslearningtech/webdev1-sonar-scanner"
    entrypoint: [""]
  stage: test
  script:
    - /usr/local/bin/start-mongo.sh
    - /usr/local/bin/node-link-packages.sh
    - npm install
    - npm run coverage
  only:
    refs:
      - master
